- docs/hackathon/general.md
> Update hackathon discord link

- docs/hackathon/general.md
> Update getting-started link

- .github/workflows/publish-cli-image.yml
- docs/getting-started.md
This PR fixes the docs section and also the CI space format.
> Fix small docs header

- .github/workflows/test-on-push.yml
- chain-cli/chaincode-template/.devcontainer/Dockerfile.devcontainer
- chain-cli/docker/Dockerfile
- chain-cli/network/configtx-policies.yml
- chain-cli/network/fablo-post-generate.sh
- chain-cli/src/commands/network-up/index.ts
- docker/Dockerfile
- docs/getting-started.md
Reverts GalaChain/sdk#88
Closes https://github.com/GalaChain/sdk/issues/98
> Revert "Remove yq and custom fabric policies"

- chain-client/src/rest-api/RestApiClient.ts
This PR removes the duplicated code from `RestApiClient.ts`.
Closes https://github.com/GalaChain/sdk/issues/161
> Remove duplicated code

- .github/workflows/publish-on-tag.yml
> Publish `@gala-chain/connect` library from CI

- chaincode/src/allowances/checkAllowances.spec.ts
- chaincode/src/allowances/checkAllowances.ts
> fix: checkAllowances includes allowances that are not yet expired

- RELEASE_PROCESS.md
- chain-cli/src/commands/init/index.ts
- docs-ko/getting-started.md
- docs/getting-started.md
This PR updates the galachain package references and also the release process guide.
> Update galachain packages references and release process guide

- docs/getting-started.md
- docs/windows-wsl.md
This PR updates the WSL documentation to recommend Ubuntu-20.04 dist.
Closes https://github.com/GalaChain/sdk/issues/259
> Update WSL documentation to recommend Ubuntu-20.04 dist

- chain-cli/README.md
- chain-cli/src/commands/init/index.spec.ts
- chain-cli/src/commands/init/index.ts
- chain-cli/src/galachain-utils.ts
This PR fixes the init command for WSL.
Closes https://github.com/GalaChain/sdk/issues/261
> Fix init command for WSL

- chain-cli/README.md
- chain-cli/package.json
- chain-cli/src/commands/init/index.ts
- chain-cli/src/galachain-utils.ts
This PR checks the CLI version when running init command, if exists a latest version it will show a message with instructions to update it.
Closes https://github.com/GalaChain/sdk/issues/246
> Check CLI version when running init command

- chain-connect/src/GalachainConnectClient.ts
- chain-connect/src/PublicKeyClient.ts
- chain-connect/src/TokenClient.ts
fix discrepancy with address private variable and setters getters, cleanup url references in derivative clients
> connect hotfix

- .github/workflows/publish-on-tag.yml
job failed with: https://github.com/GalaChain/sdk/actions/runs/10575975247/job/29301124852
> Fix CURL command in trigger GitLab pipeline

- chain-api/src/utils/error.ts
- chaincode/src/balances/fetchOrCreateBalance.ts
- chaincode/src/burns/burnTokens.ts
- chaincode/src/services/UniqueTransactionService.ts
> Add ChainError.ignore method

- chain-api/src/types/allowance.ts
- chain-api/src/types/burn.ts
- chain-api/src/types/dtos.ts
- chain-api/src/types/lock.ts
- chain-api/src/types/mint.ts
- chain-api/src/types/token.ts
- chain-api/src/types/use.ts
- chain-connect/package.json
- chain-connect/src/ClientApi.spec.ts
- chain-connect/src/GalaChainClient.spec.ts
- chain-connect/src/GalaChainClient.ts
- chain-connect/src/Utils.spec.ts
- chain-connect/src/chainApis/PublicKeyApi.ts
- chain-connect/src/chainApis/TokenApi.ts
Removes need for duplication / redeclaration of chain-api classes for consuming libraries.
Standardize type transformation / validation across sub-projects of the mono repo
Use stronger / static typing
> Propose rework of chain-api and chain-connect type handling

- chaincode/src/fees/exitGateImplementations.ts
> fix: post mint lock supports user calling on behalf of owner

- chain-api/src/types/ChainId.ts
- chain-api/src/types/oracle.spec.ts
- chain-api/src/types/oracle.ts
- chaincode/src/fees/feeGateImplementations.ts
> fix: oracle cross rate exchange calculations, tests, documentation

- chaincode/src/fees/exitGateImplementations.ts
CHAIN-819
Bug fix for version 1.x
> fix: post-mint-lock calculation decimal handling v1

- chain-api/src/types/TokenBalance.spec.ts
- chain-api/src/types/TokenBalance.ts
- chaincode/src/locks/unlockToken.ts
> fix: lock authorities can unlock fungibles

- chain-api/src/types/mint.ts
- chaincode/src/mint/fetchMintConfigurations.ts
- chaincode/src/mint/saveMintConfiguration.ts
v1
Add mintFeeConfiguration to TokenMintConfigurationDto and saveTokenMintConfiguration methods()
> dto and save support for MintFeeConfiguration v1

- chain-api/src/types/TokenMintConfiguration.ts
- chain-api/src/types/mint.ts
- chaincode/src/fees/feeGateImplementations.ts
- chaincode/src/fees/galaFeeGate.ts
- chaincode/src/mint/fetchMintConfiguration.ts
- chaincode/src/mint/index.ts
- chaincode/src/mint/saveMintConfiguration.ts
v2
Extend TokenMintConfiguration to specify additional fees, charged in $GALA, in addition to globally-configured fee quantities for mint operations for specific token classes.
> configure additional mint fees for specific tokens v2

- chain-client/src/hf/CAClient.ts
Add a mechanism to prevent multiple simultaneous enrollment attempts for the same user, which can cause CA timeouts. Introduces a `pendingEnrollments` tracking object to manage and serialize enrollment requests.
> feat: Prevent concurrent CA enrollment with pending check

- docs/integration-guide.md
Basic guide to help new integrators understand the basics of adding GalaChain to their application.
> Integration Guide

- tools/chaincode-rules.mdc
Cursor rules (.mdc) to assist with using Cursor AI to develop chaincode.
> initial version of cursor rules document for chaincode development

- tools/scripts/update-all-snapshots.sh
> Chore: Add script to test and update snapshots in packages and chaincode template
