GalaChain/sdk

- package-lock.json
- package.json
This change makes the `nx` dep version consistent with scoped `@nx` packages.
> Pin `nx` version

- chain-api/src/types/TokenBalance.spec.ts
- chain-api/src/types/TokenBalance.ts
- chain-api/src/types/lock.ts
- chain-cli/chaincode-template/src/token/GalaChainTokenContract.ts
- chaincode/src/__test__/GalaChainTokenContract.ts
- chaincode/src/allowances/AllowanceError.ts
- chaincode/src/allowances/grantAllowance.spec.ts
- chaincode/src/allowances/grantAllowance.ts
- chaincode/src/burns/burnTokens.ts
- chaincode/src/locks/lockTokens.spec.ts
- chaincode/src/locks/lockTokens.ts
- chaincode/src/locks/unlockToken.ts
- chaincode/src/transfer/transferToken.ts
- licenses/licenses.csv
TokenBalance supports locks on fungible tokens and accounts for locked fungible quantity when calculating spendable balance. 
LockToken / UnlockToken methods support new locking api for fungible tokens on TokenBalance.
TokenBalance can possibly support multiple locks of varying quantities over the total overall fungible balance, and will unlock quantity using the holds that are set to expire soonest.
>  TokenBalance supports TokenHold locks for fungible tokens

- chain-api/src/types/ChainObject.ts
- chain-api/src/types/RangedChainObject.ts
In some cases we want to add custom serialization to chain object key part by using custom `.toStringKey()` method. For some reason we had regression with not considering it in our code. This is a fix.
> Fix nested object key parts

- .github/workflows/publish-page.yml
- docs/.pages
- docs/chaincode-post-deployment.md
- docs/index.md
- mkdocs.yml
This PR adds a new mkdocs feature to customize the doc pages order.
It also:
- updates the CI job to install the package.
- updates `chaincode-first-steps.md` to `chaincode-post-deployment.md`
It'll make the order of the pages more intuitive and also will create a flow with the "Next" button in the bottom right of the page.
> Update docs order

- chaincode/src/mint/fetchMintAllowanceSupply.ts
- chaincode/src/mint/index.ts
This PR removes an unsued function `fetchMintAllowanceSupplyForToken` for not being used anywhere within the SDK.
Closes https://github.com/GalaChain/sdk/issues/153
> Remove unused function

- chain-api/src/types/TokenMintRequest.ts
- chain-api/src/types/common.ts
- chaincode/src/mint/fulfillMintAllowance.ts
This PR adds a new input validation for `MintRequestDto` to check if the value of `timeKey` can be converted to a BigNumber.
Closes https://github.com/GalaChain/sdk/issues/155
> Add input validation for MintRequestDto

- chaincode/src/burns/fetchBurns.ts
- chaincode/src/mint/fetchMintAllowanceSupply.ts
This Pr fixes the comment typo `scensarios` to `scenarios` in `fetchBurns` and `fetchMintAllowanceSupply`.
Closes https://github.com/GalaChain/sdk/issues/159
> Fix comment typo

- chain-client/src/hf/CAClient.ts
This PR updates CAClient to use httpOptions.verify instead of a default value.
Closes https://github.com/GalaChain/sdk/issues/130
> Update CAClient to use httpOptions.verify

- chain-test/src/data/currency.ts
- chain-test/src/data/users.ts
- chaincode/src/burns/burnTokens.spec.ts
- chaincode/src/burns/burnTokens.ts
This PR adds the `owner` param to `fetchAllowancesData` to be used as filter in `grantedBy`.
Closes https://github.com/GalaChain/sdk/issues/216
> Add grantedBy as a filter when fetching allowances in burnTokens

- chain-cli/network/browser-api/browser-api-compose.sh
Fixes a small issue where I believe it is mean to be docker-compose not docker compose
> Change `docker compose` to `docker-compose` in local chain browser script 

- chaincode/src/allowances/fetchAllowances.ts
Prevent PHANTOM_READ conflicts
There isn't a straightforward way to test this in our current unit/e2e tests, as replication requires 2 concurrent transactions executing in the same block
> fix: include grantedBy in fetch allowances query

- chain-connect/src/GalaChainClient.spec.ts
- chain-connect/src/GalaChainClient.ts
- chain-connect/src/customClients/BrowserConnectClient.ts
- chain-connect/src/helpers.ts
- only attach listeners once
- add disconnect method for removing listeners & resetting local state
- fix bug that was occurring when the address was updated to an empty string (was attempting to set it as `0x` which triggered a validation error)
> GalaChainClient updates

- chaincode/src/fees/exitGateImplementations.ts
> fix: post-mint-lock decimals handling v2

- .github/workflows/manual-docs-publish.yml
- .github/workflows/manual-version-bump.yml
- .github/workflows/publish-on-tag.yml
- chain-cli/src/commands/logs/index.ts
This fix contains changes from https://github.com/GalaChain/sdk/pull/457
> Fix CLI compatibility with Node.js 18 and add manual docs publish action (backport from v2)

- chain-api/src/utils/signatures/eth.spec.ts
- chain-api/src/utils/signatures/eth.ts
This aligns with how `Wallet` in `ethers` handles private keys:
```js
const ethers = require('ethers');
const walletWithoutPrefix = new ethers.Wallet(
'0000000000000000000000000000000000000000000000000000000000000001'
);
const walletWithPrefix = new ethers.Wallet(
'0x0000000000000000000000000000000000000000000000000000000000000001'
);
console.log(walletWithPrefix.publicKey === walletWithoutPrefix.publicKey);
// true
```
> Have getPublicKey() return the correct result for private keys prefixed with 0x

- .github/workflows/publish-on-tag.yml
closes https://github.com/GalaChain/sdk/issues/472
also applies changes from: https://github.com/GalaChain/sdk/pull/487 (Python version set to 3.11 to fix docs publishing)
> Update publish workflow to support version-specific npm dist tags

- chain-api/src/validators/IsUserAlias.spec.ts
- chain-api/src/validators/IsUserAlias.ts
Enhance Ethereum user alias validation to reject addresses with '0x' prefix and update error message to clarify the expected format
> Fix: Allow Ethereum user alias without 0x prefix only

- chaincode/src/contracts/PublicKeyContract.spec.ts
- chaincode/src/services/PublicKeyService.ts
- Add test case for registering a user profile that was mistakenly registered previously with RegisterEthUser
- Modify PublicKeyService to handle existing Ethereum user profiles
> Fix: Handle registration user profiles that already registered with eth

- chaincode/src/__test__/TestGalaContract.ts
- chaincode/src/contracts/GalaContract.spec.ts
- chaincode/src/contracts/GalaContract.ts
- chaincode/src/types/GalaChainStub.ts
// Given
Batch Requests 1, 2, 3
// When
BatchRequest1:
read keyA
write keyA
successful
BatchRequest2:
write keyA <-- gets BatchRequest1's changes
error/failure
BatchRequest3:
read keyA <-- should NOT get BatchRequest2's changes
// Then
BatchRequest3 should not get BatchRequest2's changes
> fix: BatchSubmit does not preserve writes from failed transactions

- chain-api/src/types/LaunchpadDtos.ts
- chain-cli/chaincode-template/e2e/launchpad-api.spec.ts
- chaincode/src/launchpad/createSale.ts
Small change to return the `reverseBondingCurveConfiguration` object in the response from CreateSale.
> Return reverseBondingCurveConfiguration in CreateSale response

- chain-test/src/unit/fixture.ts
- chaincode/src/contracts/GalaTransaction.ts
- chaincode/src/types/GalaChainStub.spec.ts
- chaincode/src/types/GalaChainStub.ts
It addresses the case, when a submit operation is called on external chaincode, and after that call, the current chaincode fails. In such cases the only way to prevent from saving writes on chain by the external chaincode seems to be terminating the transaction with uncaught exception, and thus - not recording the transaction in history at all.
> Feat: Terminate transaction with exception when external chaincode call succeeds and subsequent calls fail

- docs/authorization.md
- Moved 'Authentication and Authorization Flow' to be after the mermaid diagram.
- Added a new section 'Optional User Registration' at the end of the document.
- Updated the 'Default admin user' section to include information about custom admin public key configuration.
- Removed duplicated content and updated internal links.
> Docs: Reorganize authorization documentation

- chain-test/project.json
- package-lock.json
- package.json
Fixes 1 critical and 6 low priority npm audit warnings
Remaining high warnings will require re-working chain-client to use fabric-gateway instead of fabric-network -
The remaining 4 high severity warnings are due to fabric-network no longer receiving updates.
jsrsasign  <11.0.0
Severity: high
Marvin Attack of RSA and RSAOAEP decryption in jsrsasign - https://github.com/advisories/GHSA-rh63-9qcf-83gf fix available via `npm audit fix --force`
Will install fabric-network@1.4.20, which is a breaking change node_modules/jsrsasign
fabric-ca-client  *
Depends on vulnerable versions of fabric-common
Depends on vulnerable versions of jsrsasign
node_modules/fabric-ca-client
fabric-common  >=2.1.1-snapshot.390
Depends on vulnerable versions of jsrsasign
node_modules/fabric-common
fabric-network …
> fix: most npm audit warnings
